### ISSUE TITLE
[TASK] Implement LLM Guardrails

### ISSUE THREAD

**Issue by rithvik-doshi** [SEMOSS/semoss#245]
### Description 

Implements guardrails to handle PHI, PII, and toxic language, ensuring safe interactions. This feature enhances system security by automatically filtering sensitive or harmful content. By protecting user data and maintaining compliance with regulations, it ensures a safer and more secure user environment.

This is a feature of medium priority as per the AI Core Feature Roadmap. Ticket requirements need to be clarified before development can start

### Existing/Reference

Common sources:
- https://github.com/guardrails-ai/guardrails
- https://cookbook.openai.com/examples/how_to_use_guardrails

This issue references. . .

### Tasks

- [ ] Expose guardrails as an engine
- [ ] On the agent builder flow, show/expose the guardrails that are available (as opposed to current preset list)
- [ ] Update the syntax on the agent builder to append the guardrail into the notebook

~~### Questions for sprint meeting discussion (1/21/24)~~

- [ ] ~~New (be) interface for guardrails? Or is the interface going to be a general reactor~~
- [ ] ~~Kinds of guardrails to implement? Anything that they could use for their client applications~~
- [ ] ~~What kinds of ui changes needed for the model creation and editing to change the mandatory guardrails?~~
- [ ] ~~What kinds of ui changes needed for applying the guardrails at the app (agent builder flow) level?~~

**Comment by johbaxter** [comment]
@ppatel9703 and @rithvik-doshi can be added on planning calls for this

**Comment by kyang4** [comment]
Are the three unchecked tasks in this ticket still being worked on? @themaherkhalil
