### ISSUE TITLE
[TASK] Implement Team Personas

### ISSUE THREAD

**Issue by rithvik-doshi** [SEMOSS/semoss#246]
WIP: Work In Progress Ticket. Tasks and Description will be updated. Attach all development branches to this ticket i.e., for each task, create a dev branch and link it to this ticket. Once all dev branches are created, this ticket will be consider completed.

### Description 

A **team persona** is a set of privileges granted to the user. This helps segregate work into specific teams, such as LLM and database teams, and enables seamless switching between team contexts. It includes a Team Admin role for user management and theming. This feature enhances collaboration and organization by clearly defining team roles and responsibilities, improving overall productivity and team dynamics.

### Existing/References

_TBC_

### Tasks

- [ ] Decide how to modify the current access or privilege granting system to teams
- [ ] Update the security DB, smss_group table
- [ ] Implement the ability for a user to select a team persona
- [ ] Add users to a team persona
- [ ] Implement a team/persona settings page
- [ ] Implement CRUD operations for personas on the settings page
- [ ] Add more tasks...

### Questions to answer:
- Who owns a group? Is it an admin, a team lead, etc?
- How do users request access to a persona/group?
- Where is group management done in the workflow?
- How do different combinations of team personas and role personas overlap?

**Comment by johbaxter** [comment]
@ppatel9703, @rithvik-doshi, @EJV20 can be added on planning calls for this

**Comment by EJV20** [comment]
Notes from meeting with Rithvik:
Big Ideas

- [x] As a SMSS admin, I can create groups, and add people/resources to groups.
- [x] As a SMSS user, When assigned a group I have access to the those resources
- [ ] As a SMSS user, I can be assigned to a team with a role persona as some sort of admin of the team 
- [ ] As a  SMSS admin/Group Admin, I can create Role personas
- [ ] As a  SMSS admin/group admin, I can add permissions to access resources, for specific role personas
- [ ] As a  SMSS  admin/Group Admin, I can add SMSS_USER to my group
- - - - - - [x] As a SMSS admin I can add SMSS_USER to my group
- - - - - - [ ] As a Group admin I can add SMSS_USER to my group
- [ ] As a  SMSS admin/Group Admin, I can edit group members to have role personas 
- [ ] As a  SMSS admin/Group admin, when adding a SMSS_USER  to my group, I can also set their role persona
- [ ] As a  SMSS admin/Group admin, I would like to be able to edit the theming per Role persona
- [ ] As a SMSS user, I would like to be able to request being added to a group
- [ ] As a SMSS user, I would like to be able to request being assigned a persona
- [ ] As a SMSS user, I would like to have the option of switching to a team persona (on the UI, loads specific resources for persona)
- [ ] As a SMSS user, when I switch to the team persona I would like my theming to change accordingly
- [ ] As any user/admin, I would like to be able to switch into, between, or out of personas.
- [ ] As any user/admin, I would like to be able to set a default persona
- [ ] As any group user/admin, when adding a resource, only make that resource accessible by the group they are currently in the context of

Notes:
 DB Tables to look at, CUSTOMGROUPASSIGNMENT, SMSS_USER, SMSS_GROUP

Tasks:
- [ ] Add role persona column to CUSTOMGROUPASSINGMENT
- [ ] DB Tables to add: Role Persona Team Table, Role Persona Permission Table
- [ ] DB Table in themes DB: Persona-team-theme table
- [ ] DB Table to request role persona
- [ ] Custom Group assignment request table
- [ ] Crud Ops/Reactors to add Role personas
- [ ] Crud Ops/Reactors to assign role personas
- [ ] Crud Ops/Reactors to request role personas
- [ ] Crud Ops/Reactors to request teams (SMSS_GROUPS)
- [ ] Crud Ops/Reactors to create themes
- [ ] Crud Ops/Reactors to assign themes
- [ ] Permission Changes, update every group permission util where Role personas are used to account for them
- [ ] Reactors to return resources along with a map of resources to team role personas to allow UI to quickly switch between contextual team role personas.
