### ISSUE TITLE
[TASK] LLMInstructReactor additions

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss#247]
### Description 

We need generalized, inputs and outputs that come back from the LLM step task.

We also need more details surrounding the importance of that task.  (an assessment)

### Existing

LLMInstructReactor.java
semoss/py/../../../instruct.py

```
current = [
    {
        "project_ids": [
            "a24f92d0-4ab3-4d93-98d5-bfc9c1eb1b7b"
        ],
        "step": "Search online for current DC housing market prices."
    },
    {
        "project_ids": [
            "e88264c6-5505-4f88-acc3-6bcae452cbac"
        ],
        "step": "List your income and monthly expenses in a spreadsheet."
    },
    ...
]
```

```
expected = [
    {
        "project_ids": [
            "a24f92d0-4ab3-4d93-98d5-bfc9c1eb1b7b"
        ],
        "step": "Search online for current DC housing market prices.",
        "description": "This is very important to get a good understanding of what the current market price is in that particular area",
        "inputs": ["state", "zip-code"],
        "outputs": ["current-housing-prices"]
    },
    ...
]
```

### Reference

N/A

### Tasks

What we want to add to each json in response.

- [ ] Reasoning to why this step is important (extra details on the step)
- [ ] Possible inputs, for this step.  Send in this format -> ['state', 'zip-code']
- [ ] Possible outputs, for this step. Send in this format -> ['current-housing-prices']

**Comment by amrpatra** [comment]
Thanks @johbaxter
