### ISSUE TITLE
[TASK] Create and Hook Up Blocks_Template Database

### ISSUE THREAD

**Issue by rithvik-doshi** [SEMOSS/semoss#254]
### Description 

The frontend menus in the app builder are currently designated by constants. We want to create a table for blocks, more generally menu items, to be stored in the theme database.

The database will include the following fields:

| Field       | Type       | Description                          |
|-------------|------------|--------------------------------------|
| `section` | varchar  | Block Category/Menu  |
| `image` | varchar | filename of default display image     |
| `hover_image`  | varchar  | filename of hover display image        |
| `name`  | varchar  | block name   |
| `id`  | varchar  | unique block id  |
| `block_json`  | CLOB | json information describing the component |
| `classification`  | varchar  | type of block  |
| `is_deletable`  | boolean | base block or custom |
| `date added`  | datetime | created at |
| `is_latest`  | boolean | latest version |
| `hover_text` | varchar | text to display on hover |

### Existing

`default-menu.ts`, `visualization-menu.ts`

### Reference

This issue references. . .

### Tasks

- [x] Determine if files are being stored as blobs or just the filenames
- [x] #256 (converted into ListThemeData)
- [x] #258
- [x] #259
- [x] #257
- [x] #260
- [x] Decide on a name for the blocks database
- [x] Decide on names for the reactors (@neelneelneel may need to change them as names will be used for internal functionality)
- [x] Initial add images to root path in Semoss project dir
- [ ] Add more images once Nataile and Neel are done with that
- [x] Unit tests for each reactor and utils
- [x] Determine how to get image urls accessible to the frontend
- [x] Store image links in the db

**Comment by rithvik-doshi** [comment]
Names will need to be changed as they're going to be used for internal functionality

**Comment by neelneelneel** [comment]
Can you genericize slightly to accommodate notebooks and templates as well?

**Comment by johbaxter** [comment]
Expected for review end of week 12/2

**Comment by natdink** [comment]
Refer to this spreadsheet for 1) the Figma which covers what the end-state should look like and 2) the links to the individual pngs for each block in both active and hover state as well as the hover text: https://amedeloitte.sharepoint.com/:x:/r/sites/CFGAI/Shared%20Documents/Development%20and%20Design/Dev/DragAndDropTile_Images.xlsx?d=w8055694ae2d74058b0c52d27f26a8594&csf=1&web=1&e=9AVkvF

**Comment by tevanburen** [comment]
Also related to https://github.com/SEMOSS/semoss-ui/issues/382
FE PR is https://github.com/SEMOSS/semoss-ui/pull/416

**Comment by tevanburen** [comment]
Per Rithvik's request to write it down somewhere, the outstanding items on the ticket are:
1. Images need to be moved from BE to FE (so deleted from this branch)
2. Block JSONs need to be stored as correct JSON strings
